### ISSUE TITLE
error saving merged mod file. Please check the log file

### ISSUE THREAD

**Issue by michael-nt** [WojciechKrysiak/SCModManager#34]
The log file log has following output
Error saving mod!
Error saving mod!
Error saving mod!

OS: Window 10
Stellaries Version 2.26

**Comment by WojciechKrysiak** [comment]
Is this the only thing in the log file? Please attach it to the issue just
in case. Also, please provide the set of miss that you were trying to merge

**Comment by Vanifae** [comment]
I am getting a similar result here is my log output:

Error loading Mod ugc_1150813552.mod
Error loading Mod ugc_1315558378.mod
Error loading Mod ugc_1419304439.mod
Error loading Mod ugc_1421387997.mod
Error loading Mod ugc_1440681546.mod
Error loading Mod ugc_1440713713.mod
Error loading Mod ugc_1455861246.mod
Error loading Mod ugc_1504307690.mod
Error loading Mod ugc_1614958089.mod
Error loading Mod ugc_1688887083.mod
Error loading Mod ugc_1866576239.mod
Error loading Mod ugc_1893375782.mod
Error loading Mod ugc_1900830460.mod
Error loading Mod ugc_937289339.mod
System.InvalidOperationException: Document is null
   at ICSharpCode.AvalonEdit.Editing.EmptySelection.StartSelectionOrSetEndpoint(TextViewPosition startPosition, TextViewPosition endPosition)
   at ICSharpCode.AvalonEdit.Editing.SelectionMouseHandler.ExtendSelectionToMouse(MouseEventArgs e)
   at ICSharpCode.AvalonEdit.Editing.SelectionMouseHandler.textArea_MouseLeftButtonUp(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
System.InvalidOperationException: Document is null
   at ICSharpCode.AvalonEdit.Editing.EmptySelection.StartSelectionOrSetEndpoint(TextViewPosition startPosition, TextViewPosition endPosition)
   at ICSharpCode.AvalonEdit.Editing.SelectionMouseHandler.ExtendSelectionToMouse(MouseEventArgs e)
   at ICSharpCode.AvalonEdit.Editing.SelectionMouseHandler.textArea_MouseLeftButtonUp(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at SCModManager.App.Main()
Error loading Mod ugc_1150813552.mod
Error loading Mod ugc_1315558378.mod
Error loading Mod ugc_1419304439.mod
Error loading Mod ugc_1421387997.mod
Error loading Mod ugc_1440681546.mod
Error loading Mod ugc_1440713713.mod
Error loading Mod ugc_1455861246.mod
Error loading Mod ugc_1504307690.mod
Error loading Mod ugc_1614958089.mod
Error loading Mod ugc_1688887083.mod
Error loading Mod ugc_1866576239.mod
Error loading Mod ugc_1893375782.mod
Error loading Mod ugc_1900830460.mod
Error loading Mod ugc_937289339.mod
Error loading Mod ugc_1150813552.mod
Error loading Mod ugc_1315558378.mod
Error loading Mod ugc_1419304439.mod
Error loading Mod ugc_1440681546.mod
Error loading Mod ugc_1440713713.mod
Error loading Mod ugc_1455861246.mod
Error loading Mod ugc_1504307690.mod
Error loading Mod ugc_1614958089.mod
Error loading Mod ugc_1688887083.mod
Error loading Mod ugc_1866576239.mod
Error loading Mod ugc_1893375782.mod
Error loading Mod ugc_1900830460.mod
Error loading Mod ugc_937289339.mod
Error saving mod!
Error saving mod!
Error saving mod!
